# -*- coding: utf-8 -*-
"""Data_Visualization_Radar_Plot

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vqQQXy97zjHXInfec4HhbjulJzAvuYmG
"""

import pandas as pd import numpy as np
import matplotlib.pyplot as plt from math import pi
try:
df_2010 = pd.read_csv('radar_10_2.csv') df_2010['Year'] = 2010
except FileNotFoundError:
print("Error: 'radar_10_2.csv' not found.") df_2010 = pd.DataFrame()

try:
df_2019 = pd.read_csv('radar_19_2.csv') df_2019['Year'] = 2019
except FileNotFoundError:
print("Error: 'radar_2019.csv' not found.") df_2019 = pd.DataFrame()
if df_2010.empty or df_2019.empty:
print("One or both data files could not be loaded. Cannot proceed.") else:
df_combined = pd.concat([df_2010, df_2019], ignore_index=True)


if 'Unnamed: 0' in df_combined.columns:
df_combined = df_combined.drop(columns=['Unnamed: 0'])

indicator_columns = ['GDP_per_capita', 'Life_Expectancy', 'Health_Spending', 'Age'] missing_cols = [col for col in indicator_columns if col not in df_combined.columns] if missing_cols:
print(f"Error: Missing expected indicator columns: {missing_cols}") else:
df_normalized = df_combined.copy() for col in indicator_columns:
global_min = df_combined[col].min() global_max = df_combined[col].max() if global_max == global_min:

df_normalized[col + '_norm'] = 0.5 else:
df_normalized[col + '_norm'] = (df_combined[col] - global_min) / (global_max - global_min)

print("\nCombined and Normalized Data (sample):") print(df_normalized[['Group', 'Year'] + [col + '_norm' for col in
indicator_columns]].head())

groups_ordered = [ 'BRICS',
'G7',
'High-Income (Non-G7)', 'Mid-Income',
'Low-Income'
]
groups = [group for group in groups_ordered if group in df_normalized['Group'].unique()]
num_groups = len(groups)
norm_indicator_cols = [col + '_norm' for col in indicator_columns] num_vars = len(norm_indicator_cols)
angles = np.linspace(0, 2 * np.pi, num_vars, endpoint=False).tolist() angles_closed_loop = angles + angles[:1]


axis_labels_map = {
'GDP_per_capita_norm': 'GDP\nper Capita', 'Life_Expectancy_norm': 'Life Expectancy', 'Health_Spending_norm': 'Health\nSpending', 'Age_norm': 'Median Age'
}
axis_labels = [axis_labels_map.get(cat, cat.replace('norm', '').replace('', ' ').title()) for cat in norm_indicator_cols]
def create_comparative_radar_subplot(ax, group_name, data_2010_norm, data_2019_norm, angles_list_closed, attribute_labels, plot_colors):
values_2010 = data_2010_norm.tolist() values_2010 += values_2010[:1]
ax.plot(angles_list_closed, values_2010, color=plot_colors['2010'], linewidth=2, linestyle='solid', marker='o', markersize=5, label='2010', zorder=3)
ax.fill(angles_list_closed, values_2010, color=plot_colors['2010'], alpha=0.25, zorder=2)

values_2019 = data_2019_norm.tolist() values_2019 += values_2019[:1]
ax.plot(angles_list_closed, values_2019, color=plot_colors['2019'], linewidth=2, linestyle='solid', marker='o', markersize=5, label='2019', zorder=4)
ax.fill(angles_list_closed, values_2019, color=plot_colors['2019'], alpha=0.25, zorder=3)

ax.set_thetagrids( np.degrees(angles_list_closed[:-1]), labels=attribute_labels
)
for t_label in ax.get_xticklabels():
t_label.set_fontsize(9)
ax.tick_params(axis='x', pad=12) ax.set_yticks(np.arange(0, 1.01, 0.25))
ax.set_yticklabels([f"{i*100:.0f}%" for i in np.arange(0, 1.01, 0.25)], fontsize=8, color="dimgray")
ax.set_ylim(0, 1.1)


ax.set_title(group_name, size=14, y=1.15, fontweight='bold')


ax.grid(color="silver", linestyle=":", linewidth=0.7, zorder=1) ax.spines["polar"].set_color("gray")


ncols = 3
nrows = (num_groups + ncols - 1) // ncols


fig, axes = plt.subplots(figsize=(6.5 * ncols, 6.5 * nrows), nrows=nrows, ncols=ncols, subplot_kw=dict(polar=True))
axes = np.array(axes).flatten()

year_colors_plot = {'2010': '#1f77b4', '2019': '#ff7f0e'}

for i, group in enumerate(groups):
if i < len(axes):
ax = axes[i]
group_data = df_normalized[df_normalized['Group'] == group]

data_2010_vals = group_data[group_data['Year'] == 2010][norm_indicator_cols].values.flatten()
data_2019_vals = group_data[group_data['Year'] == 2019][norm_indicator_cols].values.flatten()

if data_2010_vals.size > 0 and data_2019_vals.size > 0: create_comparative_radar_subplot(ax, group, data_2010_vals, data_2019_vals,
angles_closed_loop, axis_labels, year_colors_plot) else:
ax.set_title(f"{group}\n(Data missing for one/both years)", size=12, y=1.1) ax.axis('off')
else:
print(f"Warning: Not enough subplots for group {group}. Adjust figure layout.")

for j in range(num_groups, len(axes)):
fig.delaxes(axes[j])


handles_legend = [plt.Line2D([0], [0], color=year_colors_plot['2010'], lw=2, marker='o', label='2010'),
plt.Line2D([0], [0], color=year_colors_plot['2019'], lw=2, marker='o', label='2019')]
fig.legend(handles=handles_legend, loc='lower center', ncol=2, fontsize=12, bbox_to_anchor=(0.5, 0.02))

fig.suptitle('Comparative Profile by Group (2010 vs 2019)', fontsize=18, fontweight='bold', y=0.985)
plt.tight_layout(rect=[0, 0.07, 1, 0.95]) plt.savefig('Per_capita_final_comparative_radar_charts_2010_vs_2019_reordered.png',
dpi=150)
print("\nComparative radar charts with reordered subplots generated and saved as comparative_radar_charts_2010_vs_2019_reordered.png")
plt.show()